name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 14
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag jondotsoy-www:latest
    - name: Docker Authorization Canister
      run: docker login cloud.canister.io:5000 -u "${{ secrets.CANISTER_USERNAME }}" -p "${{ secrets.CANISTER_PASSWORD }}"
    - name: Tag imagen
      run: npx repo-versions | xargs -I_ docker tag jondotsoy-www:latest cloud.canister.io:5000/${{ secrets.CANISTER_USERNAME }}/jondotsoy-www:_
    - run: docker images
    - run: docker push --all-tags cloud.canister.io:5000/${{ secrets.CANISTER_USERNAME }}/jondotsoy-www
